### ISSUE TITLE
Install Slack application on the GitHub repository

### ISSUE THREAD

**Issue by vprivat-ads** [csgroup-oss/apikey-manager#6]
We would like to be notified of apikey-manager new releases directly in our Slack instance, would it be possible to install the [Slack GitHub app](https://github.com/apps/slack/)  in this repository?

**Comment by geonux** [comment]
Hello, the Slack Github app is now installed and is being tested on apikey-manager.

**Comment by vprivat-ads** [comment]
Thank you, it works! :)
